### ISSUE TITLE
AutoCompleteSelectField has no attribute 'limit_choices_to' in Django 1.7

### ISSUE THREAD

**Issue by artscoop** [crucialfelix/django-ajax-selects#83]
This error has just happened in the admin.
My code for my `ModelAdmin` is

    form = make_ajax_form([...])
 
While this worked in Django 1.6, 1.7 has introduced a

    limit_choices_to = formfield.limit_choices_to

which is called on the AutoCompleteSelectField (at least), although it has no limit_choices_to attribute. I added this line at the end

    f.limit_choices_to = None

in `make_ajax_field` and it fixes the problem, but I don't know if this is the way to go.
